blank_issues_enabled: false
contact_links:
  - name: General question
    url: https://github.com/OwenAtConestoga/NStar-Companion/discussions
    about: For questions, use Discussions instead of Issues
